<?php
/**
 * @file
 * bibsdb_page_with_list_of_tagged_content.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function bibsdb_page_with_list_of_tagged_content_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_bibsdb_tags_to_expand'
  $field_bases['field_bibsdb_tags_to_expand'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_bibsdb_tags_to_expand',
    'foreign keys' => array(
      'format' => array(
        'columns' => array(
          'format' => 'format',
        ),
        'table' => 'filter_format',
      ),
    ),
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 255,
      'profile2_private' => FALSE,
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  // Exported field_base: 'field_bibsdb_weight'
  $field_bases['field_bibsdb_weight'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_bibsdb_weight',
    'foreign keys' => array(),
    'indexes' => array(),
    'locked' => 0,
    'module' => 'number',
    'settings' => array(
      'profile2_private' => FALSE,
    ),
    'translatable' => 0,
    'type' => 'number_integer',
  );

  return $field_bases;
}
